exports.language = {
  nav: {
    product: {zh: '产品', en: 'Product'},
    video: {zh: '视频', en: 'Video'},
    phone: {zh:'0512 - 8888 0000',en:'0512 - 8888 0000'},
    register: {zh: '创建账户', en: 'Register'},
    login: {zh: '登入', en: 'Login'},
    logout: {zh: '退出', en: 'Logout'}
  },
  footer: {
    beianhao: {zh: '版权所有', en: 'All rights reserved'},
    service: {zh: '服务', en: 'Service'},
    contactus: {zh: '联系我们', en: 'Contact us'},
    shipping: {zh: '物流与配送', en: 'Logistics and Distribution'},
    info: {zh: '保修信息&产品注册', en: 'Warranty & Product Registration'},
    returns: {zh: '退换货政策', en: 'Return Policy'},
    zhiFu: {zh: '在线支付', en: 'Online Payment'},
    company: {zh: '企业', en: 'Company'},
    aboutus: {zh: '关于我们', en: 'About us'},
    joinus: {zh: '加入我们', en: 'Join us'},
    partners: {zh: '合作伙伴', en: 'Partners'},
    methods: {zh: '选购指引', en: 'Guidance'},
    men: {zh: '男子选购指引', en: "Men's Guidance"},
    women: {zh: '女子选购指引', en: "Women Guidance"},
    size: {zh: '尺码说明', en: "Size Description"}
  },
  index:{
    products:{zh:'产品',en:'Products'},
    more:{zh:'阅读更多',en:'More'},
    productsTui:{zh:'产品推荐',en:'Product recommendation'}
  },
  login: {
    title: {zh: '登入', en: 'Login'},
    login: {zh: '账户登入', en: 'Login'},
    register: {zh: '账户注册', en: 'Register'},
    account: {zh: '登入邮箱/昵称', en: 'Emai address/Name'},
    password: {zh: '输入密码', en: 'Password'},
    dengru: {zh: '登入', en: 'Login'},
    remember: {zh: '记住密码', en: 'Remember password'},
    forget: {zh: '忘记密码', en: 'Forget password'},
    error1before:{zh:'对不起，此帐号还没有被激活，激活链接已发送到',
      en:'I am sorry, this account has not been activated, the activation link has been sent to '},
    error1after:{zh:'邮箱，请查收。',
      en:'mailbox, please check.'},
    error2:{zh:'超过80%的用户选择了验证邮箱，账户更安全购物更放心。',
      en:'More than 80% of users chose the verification email, accounts more secure shopping more at ease.'},
    error3before:{zh:'系统已想你的邮箱',
      en:'System has your mailbox '},
    error3after:{zh:'发送了一封验证邮件，请您登陆邮箱，点击邮件中的链接完成邮箱验证。',
      en:'sent a verification email, please log mailbox, click the link in the email to complete the verification mail.'},
    successBefore:{zh:'恭喜，',en:'Congratulations, '},
    successAfter:{zh:'已注册成功！',en:'has been registered successfully!'}
  },
  sign: {
    title: {zh: '注册', en: 'Register'},
    nickname: {zh: '昵称', en: "Name"},
    email: {zh: '登入邮箱', en: 'Email'},
    password: {zh: '密码', en: 'Password'},
    password2: {zh: '确认密码', en: 'Confirm password'},
    before: {zh: '带', en: 'With'},
    after: {zh: '的必填', en: 'are required'},
    confirmationMessage: {zh: '已阅读产品信息及客户服务', en: 'Have read the product information and customer service'},
    success: {zh: '注册完成', en: 'Submit'},
    textTitle: {zh: '为什么要注册？', en: 'Why do you want to register?'},
    text1: {zh: '购物方便：随时随地审查存储的信息，包括完整的订单历史记录和跟踪信息。',
      en: 'Shopping convenience: review of information stored anywhere, including complete order history and tracking information.'},
    text2: {zh: '卓越的客户服务：存储的账户信息，我们卓越的客户服务团队将能够更快的解决您的问题&关注。',
      en: 'Excellent customer service: Account information is stored, our excellent customer service team will be able to solve your problem faster & attention.'},
    text3: {zh: '分享您使用我们产品的感受：分享您使用产品的经验，帮助其他的成员找到他们适合的器材',
      en: 'Share your experience using our products: Share your experience using the product to help other members find them suitable equipment'},
    text4: {zh: '最新消息及优惠：保持更新与独家在线折扣和产品的创新。',
      en: 'Latest news and deals: Keep updated with exclusive online discounts and innovative products.'}
  },
  resetfist: {
    title: {zh: '找回密码', en: 'Retrieve password'},
    searchpass: {zh: '找回密码', en: 'Retrieve password'},
    name: {zh: '输入账户名', en: 'Enter loginname'},
    identity: {zh: '验证身份', en: 'Authenticate'},
    reset: {zh: '重置密码', en: 'Reset password'},
    success: {zh: '完成', en: 'Success'},
    email: {zh: '账户名', en: 'Email'},
    email2: {zh: '登入邮箱', en: 'Email'},
    code: {zh: '验证码', en: 'Code'},
    next: {zh: '下一步', en: 'Next'},
    mailsuccess: {zh: '链接已成功发送您的邮箱，有效时间24小时，请注意查看！', en: 'Link has been successfully sent to your mailbox, effective 24 hours, please pay attention to see!'},
    changesuccess: {zh: '恭喜您，密码设置成功！您可以使用新密码登录！', en: 'Congratulations, passwords set successfully! You can use the new password!'},
    login: {zh: '登入账号', en: 'Login'},
    newpassword: {zh: '新密码', en: 'News password'},
    text1: {zh: '1、为保证您的安全，新密码必须与旧密码不同。', en: '1.in order to ensure your safety, the new password must be different from the old password.'},
    text2: {zh: '2、密码由6-18位字符（字母、数字、符号）组合而成，不能只使用一种字符，注意区分大小写。',
      en: '2.6-18 digit password combination of characters (letters, numbers, symbols) together, you can not use just one character, case sensitive. In order to ensure your safety, the new password must be different from the old password.'},
    newpassword2: {zh: '再次输入', en: 'Re-enter'},
    submit: {zh: '提交', en: 'Submit'}
  },
  contact: {
    service: {zh: '服务', en: 'Service'},
    contactus: {zh: '联系我们', en: 'Contact us'},
    shipping: {zh: '物流与配送', en: 'Logistics and Distribution'},
    info: {zh: '保修信息&产品注册', en: 'Warranty & Product Registration'},
    returns: {zh: '退换货政策', en: 'Return Policy'},
    leavemessage: {zh: '留言', en: 'Leave a message'},
    theme: {zh: '主题', en: 'Title'},
    name: {zh: '姓名', en: 'Name'},
    mail: {zh: '邮件', en: 'Email'},
    message: {zh: '内容', en: 'Message'},
    submit: {zh: '发送', en: 'Submit'},
    contactway: {zh: '联系方式', en: 'Contact'},
    email: {zh: '电子邮件', en: 'Email'},
    phone: {zh: '电话', en: 'Phone'},
    fax: {zh: '传真', en: 'Fax'},
    adress: {zh: '地址', en: 'Adress'},
    hello:{zh:'你好：',en:'Hello:'},
    success:{zh:'你的邮件已发送成功！',en:'Your message has been sent successfully!'},
    back:{zh:'返回',en:'Back'}
  },
  about: {
    title: {zh: '关于我们', en: 'About us'},
    company: {zh: '企业', en: 'Company'},
    aboutus: {zh: '关于我们', en: 'About us'},
    partners: {zh: '合作伙伴', en: 'Partners'}
  },
  order: {
    orderTitle: {zh: '全部订单', en: 'All orders'},
    receiptTitle: {zh: '待收货', en: 'Upon receipt'},
    evaluatedTitle: {zh: '待评价', en: 'To be evaluated'},
    paymentTitle: {zh: '待付款', en: 'Pending payment'},
    personalCenter: {zh: '个人中心', en: 'Personal center'},
    allOrders: {zh: '全部订单', en: 'All orders'},
    uponReceipt: {zh: '待收货', en: 'Upon receipt'},
    toBeEvaluated: {zh: '待评价', en: 'To be evaluated'},
    pendingPayment: {zh: '待付款', en: 'Pending payment'},
    returnGoods: {zh: '退换货', en: 'Return of goods'},
    confirmPaying: {zh: '确认付账', en: 'Confirm paying'},
    cancelOrder: {zh: '取消订单', en: 'Cancel Order'},
    totalPrice: {zh: '总价', en: 'Total price'},
    detail: {zh: '展开订单详情', en: 'Expand the order details'},
    orderDetails: {zh: '订单详情', en: 'Order details'},
    ordersAccount: {zh: '订单账号', en: 'Orders Account'},
    singleTime: {zh: '下单时间', en: 'Single time'},
    ordeStatus: {zh: '订单状态', en: 'Order Status'},
    paymentInformation: {zh: '支付信息', en: 'Payment Information'},
    payment: {zh: '支付方式', en: 'Mode of payment'},
    paidTime: {zh: '支付时间', en: 'Paid time'},
    deliveryInformation: {zh: '配送信息', en: 'Delivery Information'},
    deliveryAddress: {zh: '配送地址', en: 'Delivery address'},
    sentTime: {zh: '发件时间', en: 'Sent Time'},
    pickupTime: {zh: '收件时间', en: 'Pick-up time'},
    confirmReceipt: {zh: '确认收货', en: 'Confirm receipt'},
    viewLogistics: {zh: '查看物流', en: 'Logistics'},
    evaluate: {zh: '评价', en: 'Evaluate'},
    changePassword: {zh: '修改密码', en: 'Change Password'},
    name: {zh: '昵称', en: 'Name'},
    email: {zh: '邮箱', en: 'Email'},
    address: {zh: '地址', en: 'Address'},
    tel: {zh: '电话', en: 'Tel'},
    code: {zh: '邮编', en: 'Zip Code'},
    curPass: {zh: '原始密码', en: 'Old password'},
    pass: {zh: '新密码', en: 'New password'},
    rePass: {zh: '确认密码', en: 'Confirm password'},
    sub: {zh: '确认', en: 'Confirm'},
    back: {zh: '返回', en: 'Back'},
    tiShi: {zh: '密码由6-16为半角字符（字母、下划线、数字）组成，区分大小写。',
      en: '6-16 digit password from the half-width characters (letters, underscores, numbers), with case-sensitive.'},
    deliveryDetails:{zh:'物流详情',en:'Delivery Details'},
    logisticsCompany:{zh:'物流公司',en:'Logistics company'},
    waybillNumber:{zh:'运单号码',en:'Waybill number'},
    biaoti:{zh:'标题',en:'Title'},
    message:{zh:'留言',en:'Message'},
    delOrder:{zh:'您确定要取消该订单吗？取消订单后，不能恢复。',
      en:'Are you sure you want to cancel the order? After the cancellation of orders, can not be restored.'},
    delOrder2:{zh:'请选择取消订单的理由：',
      en:'Please select the reason for cancellation of orders:'},
    yuanYin1:{zh:'不想买了',en:'Do not want to buy'},
    yuanYin2:{zh:'找了别家',en:'Find another home'},
    yuanYin3:{zh:'缺货',en:'Out of stock'},
    yuanYin4:{zh:'其他原因',en:'Other reasons'},
    yuanYin5:{zh:'信息填错，重新拍',en:'Information incorrectly, re-shoot'},
    return:{zh:'退货',en:'Return of goods'},
    easeOfUse:{zh:'易用性',en:'Ease of Use'},
    productQuality:{zh:'产品质量',en:'Product Quality'},
    effectiveness:{zh:'有效性',en:'Effectiveness'},
    attitude:{zh:'服务态度',en:'Attitude'},
    submit:{zh:'确认提交',en:'Submit'},
  },
  returnGoods:{
    returnGoods:{zh:'您确定要选择退货吗？选择退货后请联系客服。',
      en:'Are you sure you want to choose to return it? Please contact customer service later choose to return'},
    returnGoods2:{zh:'请选择退货的理由：',
      en:'Please select the reason to return:'},
    yuanYin1:{zh:'买错了',en:'Bought the wrong'},
    yuanYin2:{zh:'发错货',en:'Wrong goods'},
    yuanYin3:{zh:'产品有损坏',en:'Products damaged'},
    yuanYin4:{zh:'其他原因',en:'Other reasons'},
    yuanYin5:{zh:'想换货',en:'Want a replacement'},
    replacement:{zh:'换货',en:'Replacement'},
    replacementText:{zh:'若想换货，须先退货，然后等钱到账后再重新选择商品并购买。',
      en:'If you want a replacement, must first return, then wait for the money credited into account and then re-select and purchase goods.'},
    replacementText2:{zh:'若造成任何困扰，请谅解。',
      en:'If you have any problems, please understand.'}
  },
  products: {
    allProducts: {zh: '所有分类', en: 'All Categories'},
    productList: {zh: '产品清单', en: 'Product List'},
    productDetails: {zh: '产品详情', en: 'Product Details'},
    productRating: {zh: '商品评价', en: 'Product Rating'},
    payment: {zh: '支付方式', en: 'Payment'},
    quantity: {zh: '数量', en: 'Quantity'},
    inventory: {zh: '库存', en: 'Inventory'},
    addcart: {zh: '加入购物车', en: 'Add to Cart'},
    buyNow: {zh: '现在购买', en: 'Buy Now'},
    productDescription: {zh: '产品说明', en: 'Product Description'},
    success:{zh:'加入购物车成功！',en:'Add to Cart success!'}
  },
  video: {
    title: {zh: '视频', en: 'Videos'},
    video: {zh: '视频', en: 'Video'}
  },
  myCart: {
    title: {zh: '我的购物车', en: 'My Cart'},
    cart: {zh: '购物车', en: 'My Cart'},
    noProduct: {zh: '您的购物车没有商品', en: 'Your shopping cart is empty'},
    noProductBefore: {zh: '继续在', en: 'Continue on the '},
    noProductAfter: {zh: '上购物，了解商品详情，或访问您的订单',
      en: 'shopping, understand the products details, or visit your order '},
    noProductAfter2: {zh: '购物车可以暂存您的商品，并且显示商品的最新价格。',
      en: 'Shopping cart can scratch your items and display the latest commodity prices.'},
    numProduct: {zh: '件商品', en: 'pieces of goods'},
    delProduct: {zh: '删除此商品', en: 'Remove this item'},
    name: {zh: '名称', en: 'Name'},
    price: {zh: '价格', en: 'Price'},
    quantity: {zh: '数量', en: 'Quantity'},
    total: {zh: '总计', en: 'Total'},
    conShop: {zh: '继续购物', en: 'Continue Shopping'},
    checkout: {zh: '去结账', en: 'Checkout'},
    delProduct2:{zh:'您是否确定删除此商品？',en:'Are you sure to remove this product?'},
    yes:{zh:'确定',en:'Yes'},
    no:{zh:'取消',en:'No'}
  },
  myOrder: {
    title: {zh: '我的订单', en: 'My order'},
    street: {zh: '收货地址', en: 'Address'},
    receiver: {zh: '收货人', en: 'Consignee'},
    tel: {zh: '手机号码', en: 'Phone'},
    postCode: {zh: '邮政编码', en: 'PostCode'},
    cancel: {zh: '取消', en: 'Cancel'},
    determine: {zh: '确定', en: 'Submit'},
    order: {zh: '下单', en: 'Order'},
    viewCart: {zh: '查看购物车并提交订单',
      en: 'View shopping cart and submit the order'},
    paymentMethod: {zh: '选择支付方式并付款',
      en: 'Select the payment method and payment'},
    confirmPayment: {zh: '确认支付', en: 'Confirm payment'},
    defaultAddress: {zh: '默认地址', en: 'The default address'},
    changeAddress: {zh: '修改地址', en: 'Modify'},
    delAddress: {zh: '删除地址', en: 'Delete'},
    addAddress: {zh: '添加新地址', en: 'Add address'},
    total: {zh: '应付总额', en: 'Total'},
    subOrder: {zh: '提交订单', en: 'Submit Order'},
    totalGross: {zh: '总共总额', en: 'Total gross'},
    payment: {zh: '支付方式', en: 'Payment'}
  },
  other:{
    continueShopping:{zh:'继续购物',en:'Continue Shopping'},
    freight:{zh:'运费',en:'Freight'},
    yuTrading:{zh:'已于',en:'Was successful transaction'},
    yuShip:{zh:'已于',en:'Was shipped'},
    yuPayment:{zh:'已于',en:'Payment was'},
    tradingSuccess:{zh:'交易成功',en:''},
    ship:{zh:'发货',en:''},
    payment:{zh:'付款',en:''}
  }
}
